name: moho
dependencies:
    - python=2.7
    - pip=8.1.2
    - future=0.15.2
    - numpy=1.11.2
    - scipy=0.18.1
    - matplotlib=1.5.3
    - basemap=1.0.7
    - pillow=3.4.1
    - numba=0.26
    - jupyter=1.0.0
    - seaborn=0.7.1
    - pip:
        - fatiando==0.4
